import { Fighter } from "./type";

export const fighters: Fighter[] = [
  {
    id: "fighter_001",
    name: "John 'The Hurricane' Doe",
    age: 29,
    weightClass: "Lightweight",
    background: "Muay Thai",
    nationality: "USA",
    stats: {
      striking: 85,
      grappling: 65,
      submission: 50,
      stamina: 80,
      defense: 70,
      mentalToughness: 75,
    },
    skills: {
      aggressiveness: 80,
      counterStriking: 70,
      clinchControl: 90,
      kickPower: 88,
      punchSpeed: 82,
      groundDefense: 60,
    },
    physical: {
      height: 173,
      weight: 70,
      reach: 177,
      speed: 85,
    },
    traits: ["Initiative Taker", "The Showman"],
    record: {
      wins: 12,
      losses: 3,
      draws: 0,
      knockouts: 8,
      submissions: 1,
      decisions: 3,
    },
    fanPopularity: 72,
  },
  {
    id: "fighter_002",
    name: "Mike 'The Beast' Johnson",
    age: 27,
    weightClass: "Middleweight",
    background: "Boxing",
    nationality: "USA",
    stats: {
      striking: 90,
      grappling: 50,
      submission: 40,
      stamina: 70,
      defense: 65,
      mentalToughness: 80,
    },
    skills: {
      aggressiveness: 85,
      counterStriking: 75,
      clinchControl: 70,
      kickPower: 80,
      punchSpeed: 90,
      groundDefense: 55,
    },
    physical: {
      height: 175,
      weight: 70,
      reach: 190,
      speed: 80,
    },
    traits: ["Dirty Boxer"],
    record: {
      wins: 14,
      losses: 2,
      draws: 0,
      knockouts: 10,
      submissions: 0,
      decisions: 4,
    },
    fanPopularity: 88,
  },
];
